### ISSUE TITLE
Handle Power Failure

### ISSUE THREAD

**Issue by leosperry** [leosperry/ha-kafka-net#29]
After a power outage, if HA comes back online before the kafka instance, HA will not load the integration.

Unfortunately, HA does not expose state of inetgrations via API. 

We might be able to check the logs, but they are not clear. Example HA log:
```
2024-02-06 07:54:05.161 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apache_kafka/__init__.py", line 152, in write
    await self._producer.send_and_wait(self._topic, payload)
  File "/usr/local/lib/python3.11/site-packages/aiokafka/producer/producer.py", line 461, in send_and_wait
    future = await self.send(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiokafka/producer/producer.py", line 444, in send
    key_bytes, value_bytes = self._serialize(topic, key, value)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiokafka/producer/producer.py", line 349, in _serialize
    self._producer_magic)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AIOKafkaProducer' object has no attribute '_producer_magic'
```
Expected Behavior:
If we can confirm kafka integration is down or no events are streaming to kafka for configurable amount of time, restart home assistant which can be done with a service call.

**Comment by leosperry** [comment]
Idea: perhaps the system monitor to call HA API to make a change and wait for response via kafka.

**Comment by leosperry** [comment]
Will not implement
